# Generated by Django 5.1.6 on 2025-02-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tarefa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
